import Form, {type State as BloodPressure} from 'components/Form';
import type {NextPage} from 'next';
import Head from 'next/head';
import {useState} from 'react';
import dayjs from 'dayjs';
import timezone from 'dayjs/plugin/timezone';
import utc from 'dayjs/plugin/utc';
import SymbolPicker from 'components/SymbolPicker';

dayjs.extend(utc);
dayjs.extend(timezone);

const Home: NextPage = () => {
  const [state, setState] = useState<BloodPressure[]>([]);

  return (
    <div>
      <Head>
        <title>Trade noted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full flex flex-col items-center">
        <h1 className=" text-sky-400 text-2xl text-bold my-6">Blood Pressure Form</h1>
        <Form onSubmit={s => setState(prev => [...prev, s])} />
      </main>

      <div className="w-full px-4">
        <ul className="w-full">
          <li className="py-3 shadow-sm">
            <span className="px-4 text-slate-900 text-bold mx-1">sys</span>
            <span className="px-4 text-slate-900 text-bold mx-1">dia</span>
            <span className="px-4 text-slate-900 text-bold mx-1">pulse</span>
          </li>
        </ul>
        <ul className="w-full">
          {state.map((bp, i) => {
            return (
              <li key={i} className="py-3 shadow-sm">
                <span className="px-4 text-slate-900 text-bold mx-1">{bp.sys}</span>
                <span className="px-4 text-slate-900 text-bold mx-1">{bp.dia}</span>
                <span className="px-4 text-slate-900 text-bold mx-1">{bp.pulse}</span>
                <span className="text-blue-200 text-xs border border-blue-200 p-1 rounded-lg">
                  {dayjs(bp.date).tz('Asia/Bangkok').format('📅 MMM DD, YY 🕜 HH:mm')}
                </span>
              </li>
            );
          })}
        </ul>
      </div>
      <SymbolPicker />
    </div>
  );
};

export default Home;
